batch_size: 100
config_filepath: null
epochs: 50
lr: 0.0001
m: cor_model_50_2
mode: encoding
n_subjects: 10
neg: 60
pos: 1
reg: 0.01
s: N
save: false
scale: 0.01
scenario: subjects
subject: null
train_size: 100000
ub: true
val_size: 1000
weights: 0.5
wind_len: 15
